variables:
  # Using git fetch is faster
  # See https://docs.gitlab.com/ce/user/project/pipelines/settings.html#git-strategy
  GIT_STRATEGY: "fetch"

  # Init submodules
  # See https://docs.gitlab.com/ee/ci/yaml/#git-submodule-strategy
  GIT_SUBMODULE_STRATEGY: "recursive"

  # Use shallow cloning to speed up git clone. This can fail, if retrying an older build on CI
  # and the old commit is not in the shallow history any more.
  # See https://docs.gitlab.com/ee/ci/yaml/#shallow-cloning
  GIT_DEPTH: "50"

  # Run `make` in parallel
  MAKEFLAGS: "-j10"

  # Pipenv cache
  PIPENV_VENV_IN_PROJECT: "true"
  PIPENV_CACHE_DIR: ".cache/"

stages:
  - environment
  - prebuild
  - build
  - test

before_script:
  - pipenv install

include:
  - ci/environment.yml
  - ci/prebuild.yml  # common, style
  - ci/core.yml
  - ci/legacy.yml
  # - ci/python.yml  TODO
  - ci/crypto.yml
  - ci/storage.yml
